### ISSUE TITLE
the fix for the colored messages fucks the hint box

### ISSUE THREAD

**Issue by yuv41** [Franc1sco/FixHintColorMessages#2]
When using the plugin the it makes the hud box background huge.. is there any fix soon?
![a](https://shibe.center/QuQo2/ZapOlehaQI455.png/raw)

**Comment by Franc1sco** [comment]
The plugin do enough line breaks for hide the text that go after the $ symbol and that is the side effect instead of have the valve text on the hud so no solution for now.

**Comment by Franc1sco** [comment]
The last update should fix it
