### ISSUE TITLE
fix for turkish language

### ISSUE THREAD

**Issue by furkan4933** [Franc1sco/FixHintColorMessages#3]
this didnt work for turkish language 
This for english version and parametre placement good for this plugin.
"SFUI_ContractKillStart"            "<font color='#45b512'>$%s1</font> to eliminate the <font color='#e58816'>High Value Target</font>."
tihs version for turkish. and didnt work can you fix?
"SFUI_ContractKillStart"    "<font color='#e58816'>Yüksek Değerli Hedefi</font> ortadan kaldırırsan <font color='#45b512'>$%s1</font> alacaksın."

**Comment by furkan4933** [comment]
![A2dsız](https://user-images.githubusercontent.com/58443116/69988203-3d68c780-1552-11ea-9613-46d672ee7382.png)
![Ad2sız](https://user-images.githubusercontent.com/58443116/69988204-3d68c780-1552-11ea-9dc2-0a3934b5cb42.png)

**Comment by Franc1sco** [comment]
https://github.com/xMaZax/fix_hint_dollar
