### ISSUE TITLE
CS:GO doesnt work with rpg plugin

### ISSUE THREAD

**Issue by csestonia** [Franc1sco/FixHintColorMessages#4]
Did not work for me! tried 5 different plugins Franc1scos and fenix!
It is very strange it actually worked (the fenix plugin) but after I started updading levels ranks it just stoped working (i did put back the same version of levelsranks by now)! I didnt touch anything else! and by now I updated sm, exts and stuff! but still
I dont understand whats the issue!
I seriously tried 5 different plugins! ofcourse I didnt do restart for server I hope this is not a big issue! I tried to play with sm plugins load/unload and also with changing map!
<img width="794" alt="Screen Shot 2019-12-02 at 10 26 47 am" src="https://user-images.githubusercontent.com/58268449/70048129-47caa600-15d2-11ea-9762-a478289f0550.png">
<img width="536" alt="Screen Shot 2019-12-02 at 10 26 32 am" src="https://user-images.githubusercontent.com/58268449/70048131-48633c80-15d2-11ea-80e4-c2f44a0df4e3.png">

**Comment by csestonia** [comment]
Update:
It did fix [SHOP] Roll Hint box!
But still the screenshot from above is not working!

**Comment by wanted241** [comment]
https://github.com/Franc1sco/FixHintColorMessages/pull/7
